-- ═══════════════════════════════════════════════════════════════
-- Norvyn Motors — Dev Seed Data
-- Run after applying 001_initial_schema.sql
-- ═══════════════════════════════════════════════════════════════

INSERT INTO vehicles (
  slug, status, category, make, model, year, trim,
  stock_id, mileage_km, price_eur, price_visible,
  exterior_color, interior_color, fuel_type, transmission,
  engine_cc, power_kw, features,
  description_de, description_en,
  import_ready, featured, sort_order
) VALUES
(
  'genesis-g80-sport-2023',
  'available',
  'luxury',
  'Genesis',
  'G80',
  2023,
  'Sport',
  'KCI-2024-001',
  12000,
  65900.00,
  true,
  'Uyuni White',
  'Black Nappa Leather',
  'petrol',
  'automatic',
  2497,
  224,
  ARRAY['Panoramadach', 'Head-up Display', 'Nappa-Leder', 'Belüftete Sitze', 'Surround-View Monitor', 'Lexicon Premium Sound'],
  'Der Genesis G80 Sport kombiniert koreanische Ingenieurskunst mit europäischem Luxusanspruch. Dieser tadellose Jahrgang 2023 wurde direkt aus Korea importiert und ist vollständig für den deutschen Markt vorbereitet.',
  'The Genesis G80 Sport combines Korean engineering with European luxury standards. This immaculate 2023 example was imported directly from Korea and is fully prepared for the German market.',
  true,
  true,
  1
),
(
  'kia-ev6-gt-2023',
  'available',
  'performance',
  'Kia',
  'EV6',
  2023,
  'GT',
  'KCI-2024-002',
  8500,
  59900.00,
  true,
  'Runway Red',
  'Black Microfiber',
  'electric',
  'automatic',
  NULL,
  430,
  ARRAY['77,4-kWh-Batterie', '800V Schnellladen', 'Sportpaket', 'HUD', 'Meridian Sound', 'Drift-Modus'],
  'Der Kia EV6 GT ist die Hochleistungsvariante der EV6-Baureihe. Mit 430 kW beschleunigt er in 3,5 Sekunden auf 100 km/h — direkt importiert aus Südkorea.',
  'The Kia EV6 GT is the high-performance variant of the EV6 lineup. With 430 kW it accelerates from 0-100 km/h in 3.5 seconds — imported directly from South Korea.',
  true,
  true,
  2
),
(
  'bmw-5er-520i-korea-2022',
  'available',
  'german_from_korea',
  'BMW',
  '5er',
  2022,
  '520i M-Sport',
  'KCI-2024-003',
  31000,
  44900.00,
  true,
  'Sophistograu Metallic',
  'Cognac Dakota Leder',
  'petrol',
  'automatic',
  1998,
  135,
  ARRAY['M-Sportpaket', 'Driving Assistant Professional', 'Park Assistant Plus', 'Harman Kardon', 'Glasdach', 'Komfortzugang'],
  'Dieser BMW 520i M-Sport wurde in Südkorea vorkonfiguriert und befindet sich in einem außergewöhnlichen Pflegezustand. Vollständige Herstellerausstattung, TÜV-bereit.',
  'This BMW 520i M-Sport was pre-configured in South Korea and is in exceptional condition. Full manufacturer specification, TÜV-ready.',
  true,
  false,
  3
);
